%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /mnt/1A9286BD92869CBF/Dataset/Kitti/dataset/sequences/05

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 5
num_features_tracking: 5
num_features_tracking_bad: 5
num_features_needed_for_keyframe: 80

chi2_th: 15.991

video_id: 1

plot:
  size: [150, 50]
  maxmin: [1000.0, 0.0]
  item_width: 5

plot0:
  inherit: plot
  maxmin: [200, 0]

plot1:
  inherit: plot
  maxmin: [1, 0]

plot_vars:
  - frame_mp_assoc_cnts
  - init_cnts

gftt_radius: 2
triangulation_log: 0
pose_estimation_log: 0
features_log: 1
isw_block: 1
reset_wait: 0

feature_track_font: 2.5
show_text: 1
text_gap: 45

# Parameters of Viewer
# in milliseconds
waitKey_time: 100
sleep_time: 5
